language: node_js
sudo: false
notifications:
  email: false
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
before_script:
- npm install
script:
- npm run test:chrome:ci
env:
- MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
branches:
  only:
    - master
    - develop
